begin;

create table if not exists public.insider_transactions (
    id bigint generated by default as identity primary key,
    report_date date not null,
    stock_code text not null,
    market text not null,
    report_type text not null,
    transaction_type text not null,
    insider_name text not null,
    insider_role text not null,
    shares_changed bigint not null,
    source text not null,
    source_record_key text not null,
    transfer_method text,
    transferee text,
    current_shares bigint,
    planned_shares bigint,
    after_shares bigint,
    effective_period text,
    reason text,
    raw_data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint insider_transactions_stock_code_fkey
        foreign key (stock_code) references public.stocks(stock_code),
    constraint insider_transactions_market_check
        check (market in ('TWSE', 'TPEX')),
    constraint insider_transactions_report_type_check
        check (report_type in ('planned_transfer', 'untransferred', 'after_report')),
    constraint insider_transactions_transaction_type_check
        check (transaction_type in ('buy', 'sell', 'transfer', 'untransferred', 'other')),
    constraint insider_transactions_stock_code_not_blank
        check (btrim(stock_code) <> ''),
    constraint insider_transactions_insider_name_not_blank
        check (btrim(insider_name) <> ''),
    constraint insider_transactions_insider_role_not_blank
        check (btrim(insider_role) <> ''),
    constraint insider_transactions_shares_changed_nonnegative
        check (shares_changed >= 0),
    constraint insider_transactions_current_shares_nonnegative
        check (current_shares is null or current_shares >= 0),
    constraint insider_transactions_planned_shares_nonnegative
        check (planned_shares is null or planned_shares >= 0),
    constraint insider_transactions_after_shares_nonnegative
        check (after_shares is null or after_shares >= 0),
    constraint insider_transactions_source_key_unique
        unique (source, source_record_key)
);

create index if not exists idx_insider_transactions_stock_date
    on public.insider_transactions (stock_code, report_date desc, id desc);

create index if not exists idx_insider_transactions_report_type
    on public.insider_transactions (report_type, report_date desc);

alter table public.insider_transactions enable row level security;

-- Insider rows are written by the desktop service-role client and read by the
-- mobile-web server using the same server-side key.  Keep direct public Data
-- API access disabled because the table contains named individuals.
revoke all on table public.insider_transactions from anon, authenticated;
grant select, insert, update, delete on table public.insider_transactions to service_role;
grant usage, select on sequence public.insider_transactions_id_seq to service_role;

comment on table public.insider_transactions is
    'TWSE/TPEx official insider share-transfer disclosures. Planned transfers and non-transfer notices are explicitly separated from future after-report rows.';
comment on column public.insider_transactions.report_type is
    'planned_transfer and untransferred come from the daily OpenAPI feeds; after_report is reserved for MOPS monthly realized-change disclosures.';
comment on column public.insider_transactions.shares_changed is
    'Non-negative share count; transaction_type/report_type identifies its meaning.';
comment on column public.insider_transactions.raw_data is
    'Original official source row retained for auditability.';

commit;

